### ISSUE TITLE
Faulty preprocessing for public bodies?

### ISSUE THREAD

**Issue by Judith-Kunz** [CorrelAid/fds_dashboard#21]
The public bodies table is not readable with my Windows system. I checked the data and the file public_bodies.csv that is created during preprocessing the .pbz2 files looks faulty to me. Is this peculiar to my system? How is the data supposed to look like?

**Comment by Judith-Kunz** [comment]
No, sorry for the misunderstanding, I meant I cannot read the data in Postgres with TABLE or a SFW statement. Regarding the csv, is the data correctly formatted? It seems like there are some missing columns in many rows, without enough delimiters.

**Comment by jstet** [comment]
Could you link the part of the code that doesn't work?

Looking at the csv in gnumeric it seems to be ok idk

**Comment by Judith-Kunz** [comment]
The issue was due to a different encoding on the client side, therefore it's closed.
