### ISSUE TITLE
Variable name change: first_message->created_at

### ISSUE THREAD

**Issue by Judith-Kunz** [CorrelAid/fds_dashboard#29]
For the initialization of the db, the script as well as the data include the old variable name. Hence, the variable in the data has to be changed as well as the in script.

**Comment by Judith-Kunz** [comment]
Should this be resolved by 
a) an extra step to match the variable first_name in the data to the corrected variable in the db
b) changing the variable name in the data and the db indefinitely 
c) taking care of this in the first update (wouldn't do that)
?

**Comment by jstet** [comment]
i vote for b) but dont understand what you mean with c)

**Comment by Judith-Kunz** [comment]
I meant writing extra code to change the variable name in the db which would be to be executed once when the update script is initialized. Seems impractical, though

**Comment by jstet** [comment]
Lets do b) then? see #30

**Comment by Judith-Kunz** [comment]
Yes. Closing this issue.
