### ISSUE TITLE
Reaction time seems too high

### ISSUE THREAD

**Issue by jstet** [CorrelAid/fds_dashboard#72]
1835120 days as initial reaction time

**Comment by xeniasaar** [comment]
Du musst das noch umrechnen. 1835120.4696 ist das Ergebnis in diesem Python Zeitspeicher Format. Das musst du noch in Tage umrechnen und dann sollten da gerundet 20 Tage rauskommen. Selbes wahrscheinlich auch bei der resolved time.

**Comment by xeniasaar** [comment]
Das hier wäre genau die Query (habs aus dem cmd Fenster) falls du's selbst nochmal in DBeaver testen willst:

SELECT avg(anon_1.time) AS avg_1
FROM (SELECT anon_2.id AS id, anon_2.min_1 - anon_3.min_2 AS time
FROM (SELECT messages.foi_request_id AS id, min(messages.timestamp) AS min_1
FROM messages
WHERE messages.sender_public_body_id IS NOT NULL AND messages.recipient_public_body_id IS NULL GROUP BY messages.foi_request_id) AS anon_2 JOIN (SELECT messages.foi_request_id AS id, min(messages.timestamp) AS min_2
FROM messages
WHERE messages.sender_public_body_id IS NULL AND messages.recipient_public_body_id IS NOT NULL GROUP BY messages.foi_request_id) AS anon_3 ON anon_2.id = anon_3.id) AS anon_1

**Comment by jstet** [comment]
https://github.com/CorrelAid/fds_dashboard/commit/0be679b1de062cf8196c5159c80ca7824e8b5ce5
