### ISSUE TITLE
possible error: Percentage costs 

### ISSUE THREAD

**Issue by jstet** [CorrelAid/fds_dashboard#79]
![2023-06-24_16-57](https://github.com/CorrelAid/fds_dashboard/assets/67161972/5373e46a-b9aa-488a-9eff-906be4c175c7)

When calculating the percentage of requests ending in withdrawal because of costs, thus a larger number than what the api calculates for the percentage of requests where the state wants money. @xeniasaar ideas?

**Comment by xeniasaar** [comment]
Ja, das basiert auf unterschiedlichen 100%. Die percentage costs sind diejenigen die Kosten aufweisen auf alle Anfragen gerechnet (also auch diejenigen die noch nicht abgeschlossen sind). Das mit dem withdrew basiert auf einer geringeren Anzahl (nur den abgeschlossenen). Soweit die Theorie. In der Praxis sind in den Daten 480 Requests die wegen Kosten zurückgezogen wurden, obwohl keine Kosten angegeben sind.

**Comment by jstet** [comment]
Kannst du die SQL query pasten, mit der du letzteres herrausgefunden hast?

**Comment by jstet** [comment]
Okay hab in Slakc gepostet
