### ISSUE TITLE
Resolved time is 0 even though there are resolved requests

### ISSUE THREAD

**Issue by jstet** [CorrelAid/fds_dashboard#84]
category=public_body_id&selection=9464](http://127.0.0.1:3000/?category=public_body_id&selection=9464

![2023-06-26_12-30](https://github.com/CorrelAid/fds_dashboard/assets/67161972/8aac981c-b47b-4bcd-bf23-328ea64e27eb)

Resolved Time is 0 even though requests have been resolved.

**Comment by xeniasaar** [comment]
Please allow for resolved_times < one day. I set the minimum to 5 minutes but seems like there are some that were resolved that fast (I don't know how realistic this is but whatever minimum time frame i set some match them, so maybe some were actually that fast)
